### ISSUE TITLE
tripAdvisor Integration - reviews and anything else? sights?hotels? flights?

### ISSUE THREAD

**Issue by esrako** [TeamTravelJournal/AndroidTravelJournalApp#211]

**Comment by richardpon** [comment]
TripAdvisor may not be a possibility. I signed up for an API key, but have no idea when I will hear back. According to Quora, the trip advisor api is pretty closed. 

Many other location API's are geared towards checkins, such as Google Places, Facebook Places, and Foursquare. Yelp may be the best location integration for our app.
