### ISSUE TITLE
Profile page scrolling is broken

### ISSUE THREAD

**Issue by richardpon** [TeamTravelJournal/AndroidTravelJournalApp#224]
The profile background image is not contracting when the content is scrolled. I bisected it back to commit:

944983d3c269d451c1bdac6e947c875ffa12e4df

It has something to do with the FAB. 

@srivats666

**Comment by srivatsj** [comment]
Yes, I am working on that. The co-ordinator layout which I put for hiding the fab broke the profile scrolling.

**Comment by richardpon** [comment]
Ok, cool!

**Comment by srivatsj** [comment]
Fixed, please test. Thanks.
