### ISSUE TITLE
fyi - map view cars are scaled to initial map size

### ISSUE THREAD

**Issue by richardpon** [TeamTravelJournal/AndroidTravelJournalApp#235]
fyi, when going into the map view and long clicking, it looks like the size of the car is scaled to the initial map size. Since I have posts all over the bay area, if I zoom into SF, the cars are pretty big:

https://app.box.com/s/40u9d6r3pwpberg25vkgmlwhmydtuttj

It works fine for Jack Pilar, as his posts are clustered together. (although, I noticed that I had to be careful about scrolling before long clicking) If we demo his map view, then we probably don't need to fix this.

**Comment by esrako** [comment]
I am aware of that this animation only works for Jack Pilar and Emma Tan's profiles. Rest it looks pretty bad and problematic. This animation does not work with zoom in/out.

The reason to this issue this: For the car icons, I used GroundOverlay which covers a fixed real Google map area regardless of zoom in/out.
Possible fix: for the car icon, replace GroundOverlay usage with something that keeps its same size on screen during zoom in/out.(similar to behaviour of regular map pin)

**Comment by richardpon** [comment]
ok cool. (just wasn't sure if this was a known issue)

This is probably not worth fixing. We can just show the animation for the Jack/Emma's profile in the demo.
