### ISSUE TITLE
[Android Bootcamp] Group Project

### ISSUE THREAD

**Issue by srivatsj** [TeamTravelJournal/AndroidTravelJournalApp#3]
Ready for review /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day. Excited to see what your group comes up with! Let us know what we can do to help.
