### ISSUE TITLE
Cache parse calls locally

### ISSUE THREAD

**Issue by richardpon** [TeamTravelJournal/AndroidTravelJournalApp#56]

**Comment by richardpon** [comment]
This will enable one activity to pass a parse object id into another activity and the receiving activity will be able to load the associated parse object from memory/disk instead of over the network.

**Comment by richardpon** [comment]
Haven't had much luck with this. It seems that no objects can be read from the local datastore. I posted a question on Piazza for this: https://piazza.com/class/i996joqeoqp2z0?cid=43

**Comment by srivatsj** [comment]
Richard, did you have a look at http://guides.codepath.com/android/Building-Data-driven-Apps-with-Parse#passing-objects-between-activities ?

**Comment by richardpon** [comment]
Yeah, I did. I tried pinning the objects instead of using the cache. It's a little unclear exactly how they differ, but using pinning seemed like a better option since that was recommended for full offline functionality. I wasn't able to retrieve any pinned objects.

**Comment by richardpon** [comment]
I looked into using the cache instead of the local datastore. They are actually mutually exclusive, as Parse only supports the use of one of those methods. It looks like ParseUser has some dependency on the local datastore by using it to store the signed in user's session token.

**Comment by srivatsj** [comment]
Richard, for the background service I was able to pin posts and retrieve it from local datastore and also unpin them.

**Comment by richardpon** [comment]
Closing, as this is a nice to have, but not mandatory.
