### ISSUE TITLE
Animate and change icons on follow and like 

### ISSUE THREAD

**Issue by srivatsj** [TeamTravelJournal/AndroidTravelJournalApp#94]

**Comment by esrako** [comment]
Heart animation and heart icon done for timeline.

Still to do: follow on profile and/or detail page

**Comment by esrako** [comment]
we have a bug on heart animation - working on it.

**Comment by esrako** [comment]
bug resolved.
Remaining: if time permits add animation for follow and like on profile/detail

**Comment by esrako** [comment]
Added like animation to detail. Will not add follow animations.
